export default[{
  			name:"sysRefNo",
  			label:"登记流水号",
  			type:'text'
  		},
  		{
  			name:"custNm",
  			label:"授信客户名称",
  			type:'text'
  		},{
  			name:"selId",
  			label:"授信客户编号",
  			type:'text'
  		},
  		{
  			name:"ccy",
  			label:"币种",
  			type:'text'
  		},
  		{
  			name:"regNo",
  			label:"发票登记笔数",
  			type:'text'
  		},
  		{
  			name:"regAmt",
  			label:"发票登记金额",
  			type:'text'
  		}]