export default [{
			url:'#',
			icon:'icon-group',
			name:'客户管理',
			id:'a',
			children:[{
				url:'form_wizard?name1=cust&name2=add&id=a1',
				name:'新增',
				id:'a1'
			},{
				url:'form_wizard?name1=cust&name2=edit&id=a2',
				name:'修改',
				id:'a2'
			},{
				url:'form_wizard?name1=cust&name2=query&id=a3',
				name:'查询',
				id:'a3'
			},{
				url:'form_wizard?name1=cust&name2=del&id=a3',
				name:'删除',
				id:'a4'
			}]},
			{
				url:'#',
				icon:'icon-briefcase',
				name:'国内单笔保理',
				id:'b',
				children:[{
					url:'#',
					icon:'icon-pencil',
					name:'登记',
					id:'b1',
					children:[{
							url:'record?name1=guo&name2=dengji&name3=login&id=b11',
							name:'申请',
							id:'b11'
						},{
							url:'form_wizard?name1=guo&name2=dengji&name3=again&id=b12',
							name:'复核',
							id:'b12'
						},{
							url:'form_wizard?name1=guo&name2=dengji&name3=road&id=b13',
							name:'在途',
							id:'b13'
						},{
							url:'form_wizard?name1=guo&name2=dengji&name3=deal&id=b14',
							name:'处理',
							id:'b14'
						}]
				},{
					url:'#',
					icon:'icon-mail-forward',
					name:'转让',
					id:'b2',
					children:[{
							url:'form_wizard?name1=guo&name2=zhuan&name3=login&id=b21',
							name:'申请',
							id:'b21'
						},{
							url:'form_wizard?name1=guo&name2=zhuan&name3=again&id=b22',
							name:'复核',
							id:'b22'
						},{
							url:'form_wizard?name1=guo&name2=zhuan&name3=road&id=b23',
							name:'在途',
							id:'b23'
						},{
							url:'form_wizard?name1=guo&name2=zhuan&name3=deal&id=b24',
							name:'处理',
							id:'b24'
						}]
				},{
					url:'#',
					icon:'icon-cny',
					name:'融资',
					id:'b3',
					children:[{
							url:'form_wizard?name1=guo&name2=rong&name3=login&id=b31',
							name:'申请',
							id:'b31'
						},{
							url:'form_wizard?name1=guo&name2=rong&name3=again&id=b32',
							name:'复核',
							id:'b32'
						},{
							url:'form_wizard?name1=guo&name2=rong&name3=road&id=b33',
							name:'在途',
							id:'b33'
						},{
							url:'form_wizard?name1=guo&name2=rong&name3=deal&id=b34',
							name:'处理',
							id:'b34'
						}]
				},{
					url:'#',
					icon:'icon-credit-card',
					name:'付款',
					id:'b4',
					children:[{
							url:'form_wizard?name1=guo&name2=pay&name3=login&id=b41',
							name:'申请',
							id:'b41'
						},{
							url:'form_wizard?name1=guo&name2=pay&name3=again&id=b42',
							name:'复核',
							id:'b42'
						},{
							url:'form_wizard?name1=guo&name2=pay&name3=road&id=b43',
							name:'在途',
							id:'b43'
						},{
							url:'form_wizard?name1=guo&name2=pay&name3=deal&id=b44',
							name:'处理',
							id:'b44'
						}]
				}]
				},
				{
					url:'barPage?name1="报表"&name2="展示"',
					icon:'icon-bar-chart',
					name:'报表',
					id:'c'
				}
		]